### ISSUE TITLE
來自助教的提醒：需求規格書訂正

### ISSUE THREAD

**Issue by wu86rex** [charles041644/BaseProject#2]
這是一份來自助教的提醒和建議：
GPS路線規劃
1. 前置條件可為無，後置條件不可為無，請補上後置條件

行程規劃
1. 前置條件有誤，請重新思考並改正。ex："系統有行程"或其他？

鬧鐘提醒
1. 前置條件可為無，後置條件不可為無，請補上後置條件
2. 前置條件有誤，請重新思考並改正。ex："系統有定義鈴聲"
或其他？

好友抽卡
1. 前置後置條件有誤，請重新思考並改正

集點獎勵
1. 前置後置條件有誤，請重新思考並改正

如有更改或訂正，皆會影響後續分數(通常是加分)，請評估是否修正

**Comment by charles041644** [comment]
助教我們改完了，能幫我們看一下嗎?

**Comment by wu86rex** [comment]
我想你們對前置條件可能有些誤會
前置條件你們可以想成是系統在執行這項功能前須具備的條件
以功能3好友抽卡舉例：
"擁有一次抽取機會（每日僅有一次）"這件事是使用者擁有一次抽卡機會跟系統無關
可以改成像是"系統有其他用戶資料"等等
因此，可以再將功能3的前置條件更改
功能1的前置條件"行程開始後不能更改"嚴格來說會有點問題，這句話比較像是在解釋這項功能的使用方式，也可進行更改，或是改為無也可

**Comment by charles041644** [comment]
助教我們改完了，能幫我們看一下嗎?

**Comment by wu86rex** [comment]
已確認過了！辛苦了！

**Comment by k-bigboss99** [comment]
謝謝助教!!

**Comment by charles041644** [comment]
請問需求規格書 可以修改什麼 成績能到100

**Comment by wu86rex** [comment]
後置條件其實是可以按照案例成功失敗寫不同的，但因為是第一份的作業所以我就不要求只進行科普ww，請對以下進行修正

行程規劃
V和VI應該是同一句話，可以改一下(沒影響成績)

鬧鐘提醒
1. 後置條件有偏差，後置條件是系統最中的狀態，輸出"鈴聲響起"那後置條件應當是鈴聲響起時的狀態，而不是"顯示還有多久....."，當然也可修改輸出，依照兩者不同可能會影響動作內容，請注意

好友抽卡
1. 後置條件對應動作有偏差(概念跟鬧鐘提醒類似)，提供參考方案如：把動作IV(含)後的改(刪)掉，或是對後置條件做更改。(推薦前者比較實在)
2. 前置條件不用"所有"，"有"就好了

集點獎勵
1. 後置條件如開頭所說的可以分成成功失敗，但這裡寫"主要成功"的就好了。"如有...."類的判斷用語不需要
2. 動作III和IV合併，或是IV就不用寫"然後"了

**Comment by charles041644** [comment]
改好了 麻煩助教了 謝謝

**Comment by wu86rex** [comment]
已確認！ 辛苦了！

**Comment by charles041644** [comment]
需求規格書 中 第四點 集點獎勵 稍微修改過 麻煩過目

**Comment by wu86rex** [comment]
已確認！ 辛苦了！

**Comment by charles041644** [comment]
稍微修改麻煩助教過目

**Comment by wu86rex** [comment]
已確認！辛苦了！
