### ISSUE TITLE
來自助教的提醒：use case diagram

### ISSUE THREAD

**Issue by wu86rex** [charles041644/BaseProject#3]
右邊的Project如果我沒猜錯應該是在指server吧？
在user case diagram通常server會是系統的一部份故不用畫出！請修正
如果不是，那Project是甚麼請在以下稍作解釋！

**Comment by charles041644** [comment]
助教改好了 麻煩幫我們看一下

**Comment by wu86rex** [comment]
已確認！辛苦了！

**Comment by k-bigboss99** [comment]
助教，我們刪除了GPS功能，所以總共是四項功能+註冊登入，麻煩助教過目

**Comment by wu86rex** [comment]
收到！已確認！
