### ISSUE TITLE
來自助教的提醒：使用案例規格

### ISSUE THREAD

**Issue by wu86rex** [charles041644/BaseProject#4]
林宇辰：行程規劃
1. 系統不算行動者
1. 前置條件在這裡是"行程規劃"的前置，行程尚未規劃本身就不能更改，不能當作前置條件，請修正
2. 如果行程規畫有衝突時間會怎麼樣？替代方案是？

賴靜儀：鬧鐘提醒
1. 系統不算行動者
2. 鬧鐘可以設置1-30間的整數提醒使用者，如果今天00:10分的行程要前10分鐘提醒和00:15分的行程要前15分鐘提醒，鬧鐘發生衝突會怎麼辦？

洪宏儀：好友抽卡
1. 系統不算行動者
2. 選擇隨機好友配對是像Dcard一樣一對一的嗎？還是有可能A配到B、B配到C、C配到其他人這樣？
如果是前者，用戶總人數是基數怎麼處理？如果是後者，同一人同一天有可能收到複數好友邀請？

陳衍承：集點獎勵
1. 系統不算行動者
2. 如果有勾選完成和未完成，卻沒有填入完成度會怎麼辦？
3. 排名榜是跟誰排名？怎麼排名？

**Comment by k-bigboss99** [comment]
助教我們改好了，麻煩再幫我們確認，謝謝!!!

**Comment by wu86rex** [comment]
已確認！辛苦了！

**Comment by k-bigboss99** [comment]
鬧鐘提醒的部分有修改，麻煩助教過目，謝謝!

**Comment by wu86rex** [comment]
收到！已確認！

**Comment by wu86rex** [comment]
> 鬧鐘提醒的部分有修改，麻煩助教過目，謝謝!
關於我在上述提的問題，是否有想到解決方案？抑或是會同時響鈴？

**Comment by k-bigboss99** [comment]
助教好，我的想法是將鬧鐘提醒改成沒有與行程連動的功能，是自己獨立出來的，設定是只能一個鬧鐘，也可以將設定好的鬧鐘重設，所以不會有衝突的問題，給使用者的意思是設定一個時間內要完成甚麼或是什麼時候要開會等等，然後可以在自己定的timeline之前，輸入提醒時間，給使用者做一個提醒的動作

**Comment by k-bigboss99** [comment]
助教，請問有看到我上面的訊息嗎?

**Comment by wu86rex** [comment]
> 助教，請問有看到我上面的訊息嗎?

已確認！辛苦了！助教上周在考期中期末，所以比較晚改不好意思@@

**Comment by charles041644** [comment]
助教您好，我是做集點獎勵的功能，那我這邊 95 分請問我被扣 什麼 跟 我可以改什麼變成100。

**Comment by anthy7154** [comment]
助教，我是負責做抽卡功能的，我稍微改過抽卡功能的提示訊息，請幫我看一下。

**Comment by wu86rex** [comment]
> 助教您好，我是做集點獎勵的功能，那我這邊 95 分請問我被扣 什麼 跟 我可以改什麼變成100。

這不用擔心！只是有些操作微妙所以保留著跟後續作業比對，這兩天會都改成100的！

**Comment by wu86rex** [comment]
> 助教，我是負責做抽卡功能的，我稍微改過抽卡功能的提示訊息，請幫我看一下。

已確認！辛苦了！

**Comment by charles041644** [comment]
助教 作業五：使用案例規格 (Use Case Specification) [個人]，我這個 分數還沒改到喔

**Comment by charles041644** [comment]
麻煩您了

**Comment by wu86rex** [comment]
> 麻煩您了
你是賴靜儀嗎？我這邊是有更改的喔！能截張圖我看看嗎？
![image](https://user-images.githubusercontent.com/22427044/71520388-d642f680-28f6-11ea-9c50-db5042712af2.png)
