### ISSUE TITLE
來自助教的提醒：robustness diagram

### ISSUE THREAD

**Issue by wu86rex** [charles041644/BaseProject#5]
兩點小問題：
1. 按照你們的圖所示：每次更新使用者圖像都需要查詢行程之完成次數嗎？
2. 已設定鬧鐘資料和使用者資料是屬於Entity沒錯，但同時使用者也可以操作這些資料。請將使用者會如何更改、設定畫出來

**Comment by charles041644** [comment]
第一點應該是說，獎勵機制 可以給 使用者選擇頭像，那會需要先判斷 使用者的行程規劃 那邊的完成度。
第二點，已經改好了麻煩過目

**Comment by wu86rex** [comment]
已確認！辛苦了！

**Comment by k-bigboss99** [comment]
鬧鐘的部分，沒有寫到輸入提醒時間，已新增上去，麻煩助教過目，謝謝

**Comment by wu86rex** [comment]
已確認！辛苦了！
