### ISSUE TITLE
來自助教的提醒：activity diagram

### ISSUE THREAD

**Issue by wu86rex** [charles041644/BaseProject#6]
洪宏儀
沒有特別問題

林宇辰
沒有特別問題

賴靜儀
1. 這個鬧鐘更能只能新增？不能更改？請修正

陳衍承
1. 請畫出起點
2. "使用者的完成度"那邊不應該是用橢圓，應是菱形，判斷條件也不能用橢圓

**Comment by charles041644** [comment]
已更改 麻煩 過目

**Comment by wu86rex** [comment]
> 已更改 麻煩 過目

"檢查鬧鐘設定時間"有誤，不能自記連回自己。這邊wrong的線並未接到其他任何物件中便直接回到自己了！
"點擊重設鬧鐘"應該是連回"輸入時間"而不是那條線

**Comment by k-bigboss99** [comment]
已更改，麻煩助教過目，謝謝

**Comment by wu86rex** [comment]
> 已更改，麻煩助教過目，謝謝

已確認！辛苦了
