### ISSUE TITLE
來自助教的提醒：序列圖

### ISSUE THREAD

**Issue by wu86rex** [charles041644/BaseProject#7]
洪宏儀
沒特別問題

林宇辰
1. activity bar沒畫完全！

賴靜儀
1. 鬧鐘提醒頁面應該查不到行程吧

陳衍承
1. 頭貼沒傳回使用者或其他地方不能換頭貼喔！

**Comment by charles041644** [comment]
已更改

**Comment by charles041644** [comment]
麻煩過目

**Comment by wu86rex** [comment]
賴靜儀
"選擇鬧鐘時間"和"是否已設定鬧鐘"不該是同時進行的喔！序列圖的順序是很重要的

**Comment by k-bigboss99** [comment]
已更改，麻煩助教過目謝謝

**Comment by wu86rex** [comment]
> 已更改，麻煩助教過目謝謝

序列圖代表著整個系統的順序不會走回頭路喔！"是否已啟動鬧鐘"那邊請稍作修正

**Comment by wu86rex** [comment]
> 已更改，麻煩助教過目謝謝

已確認！辛苦了！

**Comment by k-bigboss99** [comment]
已更改，麻煩助教過目謝謝!!

**Comment by wu86rex** [comment]
> 已更改，麻煩助教過目謝謝!!

已確認！辛苦了！
